--class id : pbs.BO.HR.TRAR
--class name : Travel Request (HR)

CREATE TABLE [dbo].[pbs_HR_TRAVEL_REQ_{XXX}](
	[REQUEST_NO] [varchar](15) NOT NULL,
	[REQUEST_DATE] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[PROPOSED_BY] [varchar](15) NOT NULL,
	[PURPOSE] [nvarchar](200) NOT NULL,
	[STATUS] [varchar](15) NOT NULL,
	[DEP_DATE] [int] NOT NULL,
	[DEP_TIME] [int] NOT NULL,
	[DEPARTURE] [nvarchar](25) NOT NULL,
	[ARR_DATE] [int] NOT NULL,
	[ARR_TIME] [int] NOT NULL,
	[DESTINATION] [nvarchar](25) NOT NULL,
	[RET_DATE] [int] NOT NULL,
	[TRANSPORTATION] [nvarchar](25) NOT NULL,
	[ACCOMODATION] [nvarchar](25) NOT NULL,
	[BUDGET_CODE] [varchar](15) NOT NULL,
	[PROJECT_CODE] [varchar](15) NOT NULL,
	[CUSTOMER_CODE] [varchar](15) NOT NULL,
	[EXT_DESC0] [nvarchar](100) NOT NULL,
	[EXT_DESC1] [nvarchar](100) NOT NULL,
	[EXT_DESC2] [nvarchar](100) NOT NULL,
	[EXT_DESC3] [nvarchar](100) NOT NULL,
	[NOTES] [nvarchar](250) NOT NULL,
	[UPDATED_BY] [varchar](15) NOT NULL,
	[UPDATED] [int] NOT NULL,
	[TIMESTAMP] [timestamp] NULL,
 CONSTRAINT [PK_pbs_HR_TRAVEL_REQ_{XXX}_1] PRIMARY KEY CLUSTERED 
(
	[REQUEST_NO] ASC
)
) ON [PRIMARY]
GO
 


IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[pbs_TRAR_{XXX}_InsertUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
BEGIN
EXEC dbo.sp_executesql @statement = N'
CREATE PROCEDURE [pbs_TRAR_{XXX}_InsertUpdate]
	@REQUEST_NO System.String(15),
@REQUEST_DATE int,
@PERIOD int,
@PROPOSED_BY System.String(15),
@PURPOSE System.String(200),
@STATUS System.String(15),
@DEP_DATE int,
@DEP_TIME int,
@DEPARTURE System.String(25),
@ARR_DATE int,
@ARR_TIME int,
@DESTINATION System.String(25),
@RET_DATE int,
@TRANSPORTATION System.String(25),
@ACCOMODATION System.String(25),
@BUDGET_CODE System.String(15),
@PROJECT_CODE System.String(15),
@CUSTOMER_CODE System.String(15),
@EXT_DESC0 System.String(100),
@EXT_DESC1 System.String(100),
@EXT_DESC2 System.String(100),
@EXT_DESC3 System.String(100),
@NOTES System.String(250),
@UPDATED_BY System.String(15),
@UPDATED int,
@TIMESTAMP System.Byte[](8)
AS

SET NOCOUNT ON

IF EXISTS(SELECT REQUEST_NO FROM [pbs_HR_TRAVEL_REQ_{XXX}] WHERE [REQUEST_NO] = @REQUEST_NO)
BEGIN
	UPDATE [pbs_HR_TRAVEL_REQ_{XXX}] SET
		[REQUEST_DATE] = @REQUEST_DATE,
[PERIOD] = @PERIOD,
[PROPOSED_BY] = @PROPOSED_BY,
[PURPOSE] = @PURPOSE,
[STATUS] = @STATUS,
[DEP_DATE] = @DEP_DATE,
[DEP_TIME] = @DEP_TIME,
[DEPARTURE] = @DEPARTURE,
[ARR_DATE] = @ARR_DATE,
[ARR_TIME] = @ARR_TIME,
[DESTINATION] = @DESTINATION,
[RET_DATE] = @RET_DATE,
[TRANSPORTATION] = @TRANSPORTATION,
[ACCOMODATION] = @ACCOMODATION,
[BUDGET_CODE] = @BUDGET_CODE,
[PROJECT_CODE] = @PROJECT_CODE,
[CUSTOMER_CODE] = @CUSTOMER_CODE,
[EXT_DESC0] = @EXT_DESC0,
[EXT_DESC1] = @EXT_DESC1,
[EXT_DESC2] = @EXT_DESC2,
[EXT_DESC3] = @EXT_DESC3,
[NOTES] = @NOTES,
[UPDATED_BY] = @UPDATED_BY,
[UPDATED] = @UPDATED,
[TIMESTAMP] = @TIMESTAMP
	WHERE [REQUEST_NO] = @REQUEST_NO
END
ELSE
BEGIN
	INSERT INTO [pbs_HR_TRAVEL_REQ_{XXX}] (
		[REQUEST_NO],
[REQUEST_DATE],
[PERIOD],
[PROPOSED_BY],
[PURPOSE],
[STATUS],
[DEP_DATE],
[DEP_TIME],
[DEPARTURE],
[ARR_DATE],
[ARR_TIME],
[DESTINATION],
[RET_DATE],
[TRANSPORTATION],
[ACCOMODATION],
[BUDGET_CODE],
[PROJECT_CODE],
[CUSTOMER_CODE],
[EXT_DESC0],
[EXT_DESC1],
[EXT_DESC2],
[EXT_DESC3],
[NOTES],
[UPDATED_BY],
[UPDATED],
[TIMESTAMP]
	) VALUES (
		@REQUEST_NO,
@REQUEST_DATE,
@PERIOD,
@PROPOSED_BY,
@PURPOSE,
@STATUS,
@DEP_DATE,
@DEP_TIME,
@DEPARTURE,
@ARR_DATE,
@ARR_TIME,
@DESTINATION,
@RET_DATE,
@TRANSPORTATION,
@ACCOMODATION,
@BUDGET_CODE,
@PROJECT_CODE,
@CUSTOMER_CODE,
@EXT_DESC0,
@EXT_DESC1,
@EXT_DESC2,
@EXT_DESC3,
@NOTES,
@UPDATED_BY,
@UPDATED,
@TIMESTAMP
	)
END' 
END