--class id : pbs.BO.HR.TRARM
--class name : Travel Request Miscelaneous

CREATE TABLE [dbo].[pbs_HR_TRAVEL_REQ_MISC_{XXX}](
	[REQUEST_NO] [varchar](15) NOT NULL,
	[LINE_NO] [varchar](5) NOT NULL,
	[EXPENSES_DESC] [nvarchar](100) NOT NULL,
	[RECEIVER] [nvarchar](25) NOT NULL,
	[COMPANY] [nvarchar](25) NOT NULL,
	[EXP_NOTES] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_pbs_HR_TRAVEL_REQ_MISC_{XXX}] PRIMARY KEY CLUSTERED 
(
	[REQUEST_NO] ASC,
	[LINE_NO] ASC
)
) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[pbs_TRARM_{XXX}_InsertUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
BEGIN
EXEC dbo.sp_executesql @statement = N'
CREATE PROCEDURE [pbs_TRARM_{XXX}_InsertUpdate]
	@REQUEST_NO System.String(15),
@LINE_NO System.String(5),
@EXPENSES_DESC System.String(100),
@RECEIVER System.String(25),
@COMPANY System.String(25),
@EXP_NOTES System.String(250)
AS

SET NOCOUNT ON

IF EXISTS(SELECT REQUEST_NO,LINE_NO FROM [pbs_HR_TRAVEL_REQ_MISC_{XXX}] WHERE [REQUEST_NO] = @REQUEST_NO AND [LINE_NO] = @LINE_NO)
BEGIN
	UPDATE [pbs_HR_TRAVEL_REQ_MISC_{XXX}] SET
		[EXPENSES_DESC] = @EXPENSES_DESC,
[RECEIVER] = @RECEIVER,
[COMPANY] = @COMPANY,
[EXP_NOTES] = @EXP_NOTES
	WHERE [REQUEST_NO] = @REQUEST_NO AND [LINE_NO] = @LINE_NO
END
ELSE
BEGIN
	INSERT INTO [pbs_HR_TRAVEL_REQ_MISC_{XXX}] (
		[REQUEST_NO],
[LINE_NO],
[EXPENSES_DESC],
[RECEIVER],
[COMPANY],
[EXP_NOTES]
	) VALUES (
		@REQUEST_NO,
@LINE_NO,
@EXPENSES_DESC,
@RECEIVER,
@COMPANY,
@EXP_NOTES
	)
END' 
END