--class id : pbs.BO.HR.TRARD
--class name : Travel Request Details

CREATE TABLE [dbo].[pbs_HR_TRAVEL_REQ_DET_{XXX}](
	[REQUEST_NO] [varchar](15) NOT NULL,
	[LINE_NO] [varchar](5) NOT NULL,
	[REC_TYPE] [varchar](5) NOT NULL,
	[TRANS_DATE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](250) NOT NULL,
	[TRANS_AMT] [numeric](18, 2) NOT NULL,
	[CONV_CODE] [varchar](5) NOT NULL,
	[CONV_RATE] [numeric](18, 5) NOT NULL,
	[AMOUNT] [numeric](18, 2) NOT NULL,
	[BUDGET_CODE] [varchar](15) NOT NULL,
	[PROJECT_CODE] [varchar](15) NOT NULL,
	[EMPL_CODE] [varchar](15) NOT NULL,
	[DEPARTMENT] [varchar](15) NOT NULL,
	[UPDATED_BY] [varchar](15) NOT NULL,
	[UPDATED] [int] NOT NULL,
	[TIMESTAMP] [timestamp] NULL,
 CONSTRAINT [PK_pbs_HR_TRAVEL_REQ_DET_{XXX}_1] PRIMARY KEY CLUSTERED 
(
	[REQUEST_NO] ASC,
	[LINE_NO] ASC,
	[REC_TYPE] ASC
)
) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[pbs_TRARD_{XXX}_InsertUpdate]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
BEGIN
EXEC dbo.sp_executesql @statement = N'
CREATE PROCEDURE [pbs_TRARD_{XXX}_InsertUpdate]
	@REQUEST_NO System.String(15),
@LINE_NO System.String(5),
@REC_TYPE System.String(5),
@TRANS_DATE int,
@DESCRIPTION System.String(250),
@TRANS_AMT System.Decimal(18, 2),
@CONV_CODE System.String(5),
@CONV_RATE System.Decimal(18, 5),
@AMOUNT System.Decimal(18, 2),
@BUDGET_CODE System.String(15),
@PROJECT_CODE System.String(15),
@EMPL_CODE System.String(15),
@DEPARTMENT System.String(15),
@UPDATED_BY System.String(15),
@UPDATED int,
@TIMESTAMP System.Byte[](8)
AS

SET NOCOUNT ON

IF EXISTS(SELECT REQUEST_NO,LINE_NO,REC_TYPE FROM [pbs_HR_TRAVEL_REQ_DET_{XXX}] WHERE [REQUEST_NO] = @REQUEST_NO AND [LINE_NO] = @LINE_NO AND [REC_TYPE] = @REC_TYPE)
BEGIN
	UPDATE [pbs_HR_TRAVEL_REQ_DET_{XXX}] SET
		[TRANS_DATE] = @TRANS_DATE,
[DESCRIPTION] = @DESCRIPTION,
[TRANS_AMT] = @TRANS_AMT,
[CONV_CODE] = @CONV_CODE,
[CONV_RATE] = @CONV_RATE,
[AMOUNT] = @AMOUNT,
[BUDGET_CODE] = @BUDGET_CODE,
[PROJECT_CODE] = @PROJECT_CODE,
[EMPL_CODE] = @EMPL_CODE,
[DEPARTMENT] = @DEPARTMENT,
[UPDATED_BY] = @UPDATED_BY,
[UPDATED] = @UPDATED,
[TIMESTAMP] = @TIMESTAMP
	WHERE [REQUEST_NO] = @REQUEST_NO AND [LINE_NO] = @LINE_NO AND [REC_TYPE] = @REC_TYPE
END
ELSE
BEGIN
	INSERT INTO [pbs_HR_TRAVEL_REQ_DET_{XXX}] (
		[REQUEST_NO],
[LINE_NO],
[REC_TYPE],
[TRANS_DATE],
[DESCRIPTION],
[TRANS_AMT],
[CONV_CODE],
[CONV_RATE],
[AMOUNT],
[BUDGET_CODE],
[PROJECT_CODE],
[EMPL_CODE],
[DEPARTMENT],
[UPDATED_BY],
[UPDATED],
[TIMESTAMP]
	) VALUES (
		@REQUEST_NO,
@LINE_NO,
@REC_TYPE,
@TRANS_DATE,
@DESCRIPTION,
@TRANS_AMT,
@CONV_CODE,
@CONV_RATE,
@AMOUNT,
@BUDGET_CODE,
@PROJECT_CODE,
@EMPL_CODE,
@DEPARTMENT,
@UPDATED_BY,
@UPDATED,
@TIMESTAMP
	)
END' 
END